import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          <div className='text-2xl font-bold text-center flex justify-evenly p-4'>
            <Link href={'/'}>Home</Link>
            <Link href={'/about'}>About</Link>
            <Link href={'/blog'}>Blog</Link>
            <Link href={'/contact'}>Contact</Link>
          </div>
        </nav>
        {children}
      </body>
    </html>
  )
}
